tap "oven-sh/bun"
# Fast and simple Node.js version manager
brew "fnm"
# Distributed revision control system
brew "git"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Open source relational database management system
brew "mysql", restart_service: :changed
# Create, run, and share large language models (LLMs)
brew "ollama", restart_service: :changed
# Object-relational database system
brew "postgresql@18", restart_service: :changed, link: true
# Persistent key-value database, with built-in net interface
brew "redis", restart_service: :changed
# Cross-shell prompt for astronauts
brew "starship"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Incredibly fast JavaScript runtime, bundler, transpiler and package manager - all in one.
brew "oven-sh/bun/bun"
